#!/usr/bin/env python3
"""Step 3: split the corpus into labeling chunks.

Writes text/chunks/chunk_000.txt ... each holding `--size` lines of::

    c000123<TAB>the utterance text

plus text/chunks/INDEX.md listing every chunk with its line count and the mix of
sources in it. corpus.jsonl is already shuffled across sources, so each chunk is
a mixed sample and the chunks can be handed to parallel labelers independently.

Usage::

    python text/make_chunks.py
    python text/make_chunks.py --size 300 --out text/chunks
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
CORPUS = os.path.join(HERE, "data", "corpus.jsonl")
CHUNK_DIR = os.path.join(HERE, "chunks")
DEFAULT_SIZE = 300


def load_corpus(path: str) -> list[dict]:
    rows = []
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--size", type=int, default=DEFAULT_SIZE, help="lines per chunk")
    ap.add_argument("--out", default=CHUNK_DIR, help="output directory")
    ap.add_argument("--corpus", default=CORPUS)
    args = ap.parse_args(argv)

    if not os.path.exists(args.corpus):
        print(f"{args.corpus} not found; run build_corpus.py first", file=sys.stderr)
        return 1

    rows = load_corpus(args.corpus)
    os.makedirs(args.out, exist_ok=True)

    # clear stale chunk files so a smaller corpus does not leave orphans behind
    for old in sorted(os.listdir(args.out)):
        if old.startswith("chunk_") and old.endswith(".txt"):
            os.remove(os.path.join(args.out, old))

    chunks = []
    for start in range(0, len(rows), args.size):
        part = rows[start:start + args.size]
        idx = start // args.size
        name = f"chunk_{idx:03d}.txt"
        path = os.path.join(args.out, name)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            for row in part:
                # text is already whitespace-normalised, so no tab can appear in it
                fh.write(f"{row['id']}\t{row['text']}\n")
        chunks.append({
            "name": name,
            "n": len(part),
            "first": part[0]["id"],
            "last": part[-1]["id"],
            "sources": Counter(r["source"] for r in part),
        })

    all_sources = sorted({s for c in chunks for s in c["sources"]})
    index = [
        "# Chunk index",
        "",
        f"Generated by `text/make_chunks.py` from `text/data/corpus.jsonl`: "
        f"**{len(chunks)} chunks**, {len(rows):,} lines, {args.size} lines per chunk "
        f"(the last chunk holds the remainder).",
        "",
        "Each chunk is an independent unit of work: hand one chunk file plus "
        "`text/LABELING_PROMPT.md` to one labeler. Lines are `id<TAB>text`; the labeler must echo "
        "the `id` back on every output line. Chunks are pre-mixed across sources, so no chunk is "
        "dominated by a single corpus.",
        "",
        "| chunk | lines | id range | " + " | ".join(f"`{s}`" for s in all_sources) + " |",
        "| --- | ---: | --- | " + " | ".join("---:" for _ in all_sources) + " |",
    ]
    for c in chunks:
        counts = " | ".join(str(c["sources"].get(s, 0)) for s in all_sources)
        index.append(f"| `chunks/{c['name']}` | {c['n']} | {c['first']}-{c['last']} | {counts} |")
    totals = Counter()
    for c in chunks:
        totals.update(c["sources"])
    index.append("| **total** | " + f"{len(rows):,}" + " |  | " +
                 " | ".join(f"{totals.get(s, 0):,}" for s in all_sources) + " |")
    index += [
        "",
        "## Progress",
        "",
        "Labeled answers go to `text/data/labeled/<chunk>.jsonl`, then:",
        "",
        "```",
        "python text/merge_labels.py text/data/labeled/*.jsonl",
        "```",
        "",
    ]
    index_path = os.path.join(args.out, "INDEX.md")
    with open(index_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(index))

    print(f"wrote {len(chunks)} chunk files to {args.out}")
    print(f"wrote {index_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
