package net.sievert.modularmobai.gametest.tools;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Just enough JSON to read the frozen models' answer sheets, and not one thing more.
 *
 * <p>The tools in this package run as plain Java programs off two output directories — see {@code brainTool} in
 * {@code multiloader-loader.gradle} — with neither the game nor any of its libraries on the classpath, which is what
 * makes them start in a second instead of booting a server. Gson is the game's, so it is not there, and the answer sheets
 * are a few hundred lines of objects, arrays, numbers, strings and nulls. This reads those.
 *
 * <p>Objects come back as {@link LinkedHashMap}, arrays as {@link ArrayList}, numbers as {@link Double}, and that is the
 * whole type system. It is not a validator: malformed input fails with whatever it fails with, because the only input it
 * ever sees is generated by {@code json.dumps} three directories away.
 */
final class Json {

    private final String text;
    private int at;

    private Json(String text) {

        this.text = text;
    }

    static Object parse(String text) {

        Json json = new Json(text);
        json.space();
        Object value = json.value();
        json.space();

        if (json.at != text.length()) {

            throw new IllegalArgumentException("Trailing JSON at " + json.at);
        }

        return value;
    }

    @SuppressWarnings("unchecked")
    static Map<String, Object> object(Object value) {

        return (Map<String, Object>) value;
    }

    @SuppressWarnings("unchecked")
    static List<Object> array(Object value) {

        return (List<Object>) value;
    }

    /** One array of numbers as floats, which is every number the answer sheets carry. */
    static float[] floats(Object value) {

        List<Object> values = array(value);
        float[] numbers = new float[values.size()];

        for (int index = 0; index < numbers.length; index++) {

            numbers[index] = ((Number) values.get(index)).floatValue();
        }

        return numbers;
    }

    static int[] ints(Object value) {

        List<Object> values = array(value);
        int[] numbers = new int[values.size()];

        for (int index = 0; index < numbers.length; index++) {

            numbers[index] = (int) Math.rint(((Number) values.get(index)).doubleValue());
        }

        return numbers;
    }

    private Object value() {

        char ch = this.text.charAt(this.at);

        return switch (ch) {

            case '{' -> this.readObject();
            case '[' -> this.readArray();
            case '"' -> this.readString();
            case 't' -> this.literal("true", Boolean.TRUE);
            case 'f' -> this.literal("false", Boolean.FALSE);
            case 'n' -> this.literal("null", null);
            default -> this.number();
        };
    }

    private Object literal(String word, Object value) {

        if (!this.text.startsWith(word, this.at)) {

            throw new IllegalArgumentException("Not JSON at " + this.at);
        }

        this.at += word.length();
        return value;
    }

    private Map<String, Object> readObject() {

        Map<String, Object> map = new LinkedHashMap<>();
        this.at++;
        this.space();

        if (this.text.charAt(this.at) == '}') {

            this.at++;
            return map;
        }

        while (true) {

            this.space();
            String key = this.readString();
            this.space();
            this.at++;                                   // the colon
            this.space();
            map.put(key, this.value());
            this.space();

            char ch = this.text.charAt(this.at++);

            if (ch == '}') {

                return map;
            }

            if (ch != ',') {

                throw new IllegalArgumentException("Not JSON at " + (this.at - 1));
            }
        }
    }

    private List<Object> readArray() {

        List<Object> values = new ArrayList<>();
        this.at++;
        this.space();

        if (this.text.charAt(this.at) == ']') {

            this.at++;
            return values;
        }

        while (true) {

            this.space();
            values.add(this.value());
            this.space();

            char ch = this.text.charAt(this.at++);

            if (ch == ']') {

                return values;
            }

            if (ch != ',') {

                throw new IllegalArgumentException("Not JSON at " + (this.at - 1));
            }
        }
    }

    private String readString() {

        StringBuilder text = new StringBuilder();
        this.at++;

        while (true) {

            char ch = this.text.charAt(this.at++);

            if (ch == '"') {

                return text.toString();
            }

            if (ch != '\\') {

                text.append(ch);
                continue;
            }

            char escape = this.text.charAt(this.at++);

            switch (escape) {

                case 'n' -> text.append('\n');
                case 't' -> text.append('\t');
                case 'r' -> text.append('\r');
                case 'b' -> text.append('\b');
                case 'f' -> text.append('\f');
                case 'u' -> {

                    text.append((char) Integer.parseInt(this.text.substring(this.at, this.at + 4), 16));
                    this.at += 4;
                }

                default -> text.append(escape);          // " \ / and anything else, as itself
            }
        }
    }

    private Double number() {

        int from = this.at;

        while (this.at < this.text.length() && "+-.eE0123456789".indexOf(this.text.charAt(this.at)) >= 0) {

            this.at++;
        }

        return Double.valueOf(this.text.substring(from, this.at));
    }

    private void space() {

        while (this.at < this.text.length() && this.text.charAt(this.at) <= ' ') {

            this.at++;
        }
    }
}
